In [2]:
import numpy as np

In [4]:

roi_size=np.array([6,9,32])
scale=8
lr_roi_size = [max(int(roi / scale), 1) for roi in roi_size]
lr_roi_size

[1, 1, 4]

In [15]:
import numpy as np
vol = np.arange(64)
vol = np.reshape(vol, (4,4,4))
subvol = vol[0:1,1:,1:3]
print(vol)
print('subvol:')
print(subvol.shape)
print(subvol)
mip = np.max(subvol,axis=2)
print(f"shape of mip {mip.shape}")
print(f"mip:{mip}")




[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]

 [[48 49 50 51]
  [52 53 54 55]
  [56 57 58 59]
  [60 61 62 63]]]
subvol:
(1, 3, 2)
[[[ 5  6]
  [ 9 10]
  [13 14]]]
shape of mip (1, 3)
mip:[[ 6 10 14]]
